### PR TITLE
gather flocker diagnostics fromm all nodes in the uft cluster

### PR DESCRIPTION
**Pull request by wallnerryan**
Debugging UFT clusters with flocker diagnostics is helpful, but retrieving them to your local machine is tough. This aims to automates gathering flocker diagnostics from all nodes in a uft cluster or as definied in a uft-style `cluster.yml`

```
uft-flocker-get-diagnostics cluster.yml
Running Flocker-diagnostics on agent nodes.
 * Ran diagnostics on control node. ec2-54-183-210-219.us-west-1.compute.amazonaws.com
 * Ran diagnostics on agent node. 54.183.97.70
 * Ran diagnostics on agent node. 54.183.98.196
Gathering Flocker-diagnostics on agent nodes.
 * Gathering diagnostics on control node. ec2-54-183-210-219.us-west-1.compute.amazonaws.com
 * Gathering diagnostics on agent node. 54.183.97.70
 * Gathering diagnostics on agent node. 54.183.98.196
```

```
ls | grep .tar
clusterhq_flocker_logs_2e180842-938b-11e5-8dda-0649fef6c463.tar
clusterhq_flocker_logs_2eaf837a-938b-11e5-af5a-06c5b0d85831.tar
clusterhq_flocker_logs_30f5a448-938b-11e5-92a5-06fdbfd9dbb1.tar
```

Signed-off-by: Ryan Wallner ryan.wallner@clusterhq.com

### CODE REVIEW

**Comment by lukemarsden** [comment]
can you merge master into this branch? thanks!

**Comment by wallnerryan** [comment]
@lukemarsden something jono and I found might be useful, let me know if any changes are needed, just merged in master

**Comment by lukemarsden** [comment]
please fix typo `diagnoistics` and then merge at will! Thanks!

**Comment by wallnerryan** [comment]
@lukemarsden btw, before i merge, one note i debated was whether to whipe out any old diagnostics created by this tool on the remote nodes. But either way, this tool is re-runnable so it shouldnt matter

**Comment by lukemarsden** [comment]
I think it's fine

**Comment by lukemarsden** [comment]
thanks!

**Pull request merged**
